# Generated by Django 4.2.16 on 2025-02-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_atendente', models.EmailField(max_length=254)),
                ('data_atendimento', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=5)),
                ('nome_servico', models.CharField(max_length=255)),
                ('nome_cidadao', models.CharField(max_length=120)),
                ('telefone_cidadao', models.CharField(max_length=15)),
                ('forma_atendimento', models.CharField(choices=[('notebook', 'Notebook'), ('celular', 'Celular'), ('chat', 'Chat')], max_length=8)),
                ('problema_resolvido', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compaz.area')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('local_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compaz.localservico')),
            ],
        ),
    ]
